### ISSUE TITLE
OneAgent-OpenTelemetry探针能使用其他开源Agent替换吗？如SkyWalking-Agent

### ISSUE THREAD

**Issue by bert82503** [CloudDetail/apo#1]
我主要对贵产品的向导式辅助用户定界定位故障原因的界面，很感兴趣。非常好的创意

大部分公司可能已经有现成的追踪体系，使用OneAgent替换的成本与风险是有门槛的。

**Comment by apoProject-cheng** [comment]
谢谢建议，我们会尽快支持skywalking agent

**Comment by apoProject-cheng** [comment]
刚刚发版，已经支持skywalking agent接入了

**Comment by bert82503** [comment]
> 刚刚发版，已经支持skywalking agent接入了

nice work! thx for team!
