### ISSUE TITLE
How to scrape RocketMQ metrics?

### ISSUE THREAD

**Issue by cfy3133** [CloudDetail/apo#117]
你好，是否能加入RocketMQ中间件的监控配置

**Comment by NeJan2020** [comment]
RocketMQ provide two ways to collect metrics:

RocketMQ(>= 5.1.0) introduced a built-in [observability component](https://rocketmq.apache.org/docs/observability/01metrics#details-of-metrics), enable it by following steps:
  - Set metricsExporterType to OTLP_GRPC.
  - Set metricsGrpcExporterTarget to the endpoint provided by the apo-otel-collector service,like `apo-otel-collector-svc:4317`.
  
In this way, APO does not need to make any changes.

---
RocketMQ(>= 4.3.2) can use the official [PrometheusExporter](https://github.com/apache/rocketmq-exporter) to collect metrics
  - Install the Exporter and connect to the RocketMQ
  - Add the following configuration into `configmap/apo-grafana-alloy-config`

```text
prometheus.scrape "rocketmq" {
  targets = [
    {
      __address__ = "YOUR_RABBIT_EXPORTER_IP:5557",
      job = "integrations/rabbitmq",
    },
  ]
  scheme     = "https"
  scrape_interval = "60s"
  forward_to = [prometheus.relabel.example.receiver]
}
```

However, Rocket's PrometheusExporter is developed in Java and is very isolated under APO's existing framework, so integration is not considered for the time being.

Metrics display:

- View metrics using APO's Grafana Inspect
- Or using this simple [grafana dashboard](https://grafana.com/grafana/dashboards/10477-rocketmq-dashboard/)

**Comment by cfy3133** [comment]
> RocketMQ provide two ways to collect metrics:
> 
> RocketMQ(>= 5.1.0) introduced a built-in [observability component](https://rocketmq.apache.org/docs/observability/01metrics#details-of-metrics), enable it by following steps:
> 
> * Set metricsExporterType to OTLP_GRPC.
> * Set metricsGrpcExporterTarget to the endpoint provided by the apo-otel-collector service,like `apo-otel-collector-svc:4317`.
> 
> In this way, APO does not need to make any changes.
> 
> RocketMQ(>= 4.3.2) can use the official [PrometheusExporter](https://github.com/apache/rocketmq-exporter) to collect metrics
> 
> * Install the Exporter and connect to the RocketMQ
> * Add the following configuration into `configmap/apo-grafana-alloy-config`
> 
> ```
> prometheus.scrape "rocketmq" {
>   targets = [
>     {
>       __address__ = "YOUR_ROCKETMQ_EXPORTER_IP:5557",
>       job = "integrations/rocketmq",
>     },
>   ]
>   scheme     = "https"
>   scrape_interval = "60s"
>   forward_to = [prometheus.relabel.example.receiver]
> }
> ```
> 
> However, Rocket's PrometheusExporter is developed in Java and is very isolated under APO's existing framework, so integration is not considered for the time being.
> 
> Metrics display:
> 
> * View metrics using APO's Grafana Inspect
> * Or using this simple [grafana dashboard](https://grafana.com/grafana/dashboards/10477-rocketmq-dashboard/)

好的
