### ISSUE TITLE
作者你好，请问对服务器性能影响怎么样

### ISSUE THREAD

**Issue by cfy3133** [CloudDetail/apo#2]

**Comment by jundizhou** [comment]
您好，由于项目刚刚开源，没有整理完整的测试报告，我们会尽快进行完整的性能测试。我们有一些离散的测试报告可以先提供，见下

**Comment by cfy3133** [comment]
> 您好，由于项目刚刚开源，没有整理完整的测试报告，我们会尽快进行完整的性能测试。我们有一些离散的测试报告可以先提供，见下

谢谢作者回复，了解

**Comment by cfy3133** [comment]
作者如果能加入如下项目的对应火焰图监控具体花费时间就完美了，国产的产品会比国外的更加友好，这个开源项目非常好用
参考的开源项目：https://github.com/coroot/coroot
![image](https://github.com/user-attachments/assets/93598c5c-2d40-4bc9-bad1-ffa7fbf44020)

**Comment by apoProject-cheng** [comment]
嗯，感谢建议，这个在我们的规划当中

**Comment by cfy3133** [comment]
> 嗯，感谢建议，这个在我们的规划当中

感谢回复，希望apo越来越好

**Comment by fuwx295** [comment]
@cfy3133 
APO OneAgent的性能测试报告

# 测试结果
测试数据包括
1. TPS（Transactions Per Second）：应用每秒事务数
2. RT（Response Time）：应用程序响应时间
3. Machine-CPU：机器 CPU 总消耗

## 2000 TPS (高负载)
<ne-clipboard data="%7B%22type%22%3A%22fragment%22%2C%22name%22%3A%22%23fragment%22%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uec0a02e2%22%2C%22name%22%3A%22tableHole%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22eCGZg%22%2C%22name%22%3A%22table%22%2C%22attrs%22%3A%7B%22spacing%22%3Atrue%2C%22widthMode%22%3A%22normal%22%2C%22fitWidth%22%3Afalse%2C%22colWidths%22%3A%5B187%2C187%2C187%2C189%5D%2C%22rowCount%22%3A4%2C%22colCount%22%3A4%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u9d14541d%22%2C%22name%22%3A%22tr%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ue0728435%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A0%7D%2C%22children%22%3A%5B%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u6447a9f5%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A1%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u2647cc6b%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u7b3887c3%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22tps%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u72ca857e%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A2%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ub7fed109%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u8b38d0fa%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22rt%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u604602fb%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A3%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u64ceb913%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u1d6d9347%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22machine-cpu%20%22%7D%5D%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u6a859854%22%2C%22name%22%3A%22tr%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u04e5d11c%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A0%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uce2bea3d%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u8915ceec%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22Baseline%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uc0d36d49%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A1%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ua05a5f51%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u2589c0e8%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%222251.0%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ub1101595%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A2%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u890eebdd%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u069ad4c1%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%2276ms%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u14ef6d14%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A3%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22udd347aea%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22ufbe15e20%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%221.249C%22%7D%5D%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u9a39a1e4%22%2C%22name%22%3A%22tr%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u2640e378%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A0%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u6ae1fdec%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22ua6779fce%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22OtelAPM%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u33184b00%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A1%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ucf047f7e%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22ue66e0627%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%222247.8%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u779957e6%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A2%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uce3ce084%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u4d92556b%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%2276ms%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u47f35667%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A3%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u51cc19a4%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u92eb9b73%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%221.439C%22%7D%5D%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u18f31453%22%2C%22name%22%3A%22tr%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u4e12bd35%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A0%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u203b0bd1%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u4ef79d7a%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22OneAgent%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22udcce55f3%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A1%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u4621af96%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22ub81c30a2%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%222239.6%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ub5f1e069%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A2%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ue4f95bdb%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22ua5b55659%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%2276ms%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u613be1df%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A3%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uc36c7f47%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u60874511%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%222.122C%22%7D%5D%7D%5D%7D%5D%7D%5D%7D%5D%7D%5D%2C%22attrs%22%3A%7B%7D%7D" source="https%3A%2F%2Fkgwnvb.yuque.com%2Fgrmkz0%2Fpstx78%2Fxailmrn0ngngxrod"></ne-clipboard><div class="lake-content" typography="classic">
  | TPS | RT | machine-cpu
-- | -- | -- | --
Baseline | 2251.0 | 76ms | 1.249C
OtelAPM | 2247.8 | 76ms | 1.439C
OneAgent | 2239.6 | 76ms | 2.122C

</div>

- 只引入OtelAPM, tps下降0.14%，平均时延基本不变，机器总体cpu上升0.19C
- 部署OneAgent时，tps下降 0.5%，平均时延基本不变，机器总体cpu上升0.87C

## 500 TPS (常规负载)
<ne-clipboard data="%7B%22type%22%3A%22fragment%22%2C%22name%22%3A%22%23fragment%22%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ue84c077a%22%2C%22name%22%3A%22tableHole%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22SEMbf%22%2C%22name%22%3A%22table%22%2C%22attrs%22%3A%7B%22spacing%22%3Atrue%2C%22widthMode%22%3A%22contain%22%2C%22fitWidth%22%3Afalse%2C%22colWidths%22%3A%5B187%2C187%2C187%2C189%5D%2C%22rowCount%22%3A4%2C%22colCount%22%3A4%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uc714e22d%22%2C%22name%22%3A%22tr%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u913a692e%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A0%7D%2C%22children%22%3A%5B%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u8969674f%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A1%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u51f15447%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u35867a62%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22tps%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u8b317112%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A2%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u2811258e%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22ucb89def8%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22rt%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u193648b0%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A3%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ufc02d8bc%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u87eeeecb%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22machine-cpu%22%7D%5D%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uaeeab4be%22%2C%22name%22%3A%22tr%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u9729d61c%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A0%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ue3fb22d1%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22ud572cd3f%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22Baseline%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u375df043%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A1%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u2b37244a%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u9ca164e0%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22562.7%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u040c516a%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A2%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ubfc1c9ec%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22uee5de525%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%2276ms%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uc2093a9c%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A3%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ud1f13b87%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22ua8a1eb49%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%220.357C%22%7D%5D%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ud8f2c380%22%2C%22name%22%3A%22tr%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u9752e6ef%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A0%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u736a5c17%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u8e0fe4a8%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22OtelAPM%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uc5bde423%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A1%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u5606b3e3%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u1832b66f%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22562.3%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uc03b9bdc%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A2%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ue5f0c78e%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u2876b7f5%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%2276ms%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u2eb2fa7e%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A3%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u50247cfc%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22uda6d9675%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%220.399C%22%7D%5D%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u5130aa86%22%2C%22name%22%3A%22tr%22%2C%22attrs%22%3A%7B%22height%22%3A37%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22uae89b2eb%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A0%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u1c3d3621%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u74c74b40%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22OneAgent%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ubdd04c38%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A1%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u94b021c6%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22ud9efa11d%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%22562.3%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ua2b329f4%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A2%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ue2da1579%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u94f455d1%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%2276ms%22%7D%5D%7D%5D%7D%2C%7B%22type%22%3A%22element%22%2C%22id%22%3A%22u1b840ebd%22%2C%22name%22%3A%22td%22%2C%22attrs%22%3A%7B%22col%22%3A3%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22element%22%2C%22id%22%3A%22ufe68cd43%22%2C%22name%22%3A%22p%22%2C%22attrs%22%3A%7B%7D%2C%22children%22%3A%5B%7B%22type%22%3A%22text%22%2C%22id%22%3A%22u233c846f%22%2C%22name%22%3A%22%23text%22%2C%22attrs%22%3A%7B%7D%2C%22data%22%3A%220.546C%22%7D%5D%7D%5D%7D%5D%7D%5D%7D%5D%7D%5D%2C%22attrs%22%3A%7B%7D%7D" source="https%3A%2F%2Fkgwnvb.yuque.com%2Fgrmkz0%2Fpstx78%2Fxailmrn0ngngxrod"></ne-clipboard><div class="lake-content" typography="classic">
  | TPS | RT | machine-cpu
-- | -- | -- | --
Baseline | 562.7 | 76ms | 0.357C
OtelAPM | 562.3 | 76ms | 0.399C
OneAgent | 562.3 | 76ms | 0.546C

</div>

- 只引入OtelAPM, tps下降0.07%，平均时延基本不变，机器总体cpu上升0.04C
- 部署OneAgent时，tps下降 0.07%，平均时延基本不变，机器总体cpu上升0.18C

# 测试环境
测试应用程序 
[skywalking benchmark](https://github.com/SkyAPMTest/Agent-Benchmarks/tree/master/Benchmark-1/example)

测试机器配置
`Intel(R) Xeon(R) Platinum@2.5GHz` 8C16G

完整测试数据以及测试脚本将会在整理之后发出来

**Comment by cfy3133** [comment]
> @cfy3133 APO OneAgent的性能测试报告
> 
> # 测试结果
> 测试数据包括
> 
> 1. TPS（Transactions Per Second）：应用每秒事务数
> 2. RT（Response Time）：应用程序响应时间
> 3. Machine-CPU：机器 CPU 总消耗
> 
> ## 2000 TPS (高负载)
>  	TPS	RT	machine-cpu
> Baseline	2251.0	76ms	1.249C
> OtelAPM	2247.8	76ms	1.439C
> OneAgent	2239.6	76ms	2.122C
> * 只引入OtelAPM, tps下降0.14%，平均时延基本不变，机器总体cpu上升0.19C
> * 部署OneAgent时，tps下降 0.5%，平均时延基本不变，机器总体cpu上升0.87C
> 
> ## 500 TPS (常规负载)
>  	TPS	RT	machine-cpu
> Baseline	562.7	76ms	0.357C
> OtelAPM	562.3	76ms	0.399C
> OneAgent	562.3	76ms	0.546C
> * 只引入OtelAPM, tps下降0.07%，平均时延基本不变，机器总体cpu上升0.04C
> * 部署OneAgent时，tps下降 0.07%，平均时延基本不变，机器总体cpu上升0.18C
> 
> # 测试环境
> 测试应用程序 [skywalking benchmark](https://github.com/SkyAPMTest/Agent-Benchmarks/tree/master/Benchmark-1/example)
> 
> 测试机器配置 `Intel(R) Xeon(R) Platinum@2.5GHz` 8C16G
> 
> 完整测试数据以及测试脚本将会在整理之后发出来

好的，感谢作者回复，看来基本没啥影响，性能杠杠的
