### ISSUE TITLE
Agent 安装报错“* 'cpus' expected type 'float32', got unconvertible type 'string', value: '1'”，无法继续

### ISSUE THREAD

**Issue by itaid** [CloudDetail/apo#57]
==================================================
      ___           ___           ___             
     /\  \         /\  \         /\  \            
    /::\  \       /::\  \       /::\  \           
   /:/\:\  \     /:/\:\  \     /:/\:\  \          
  /::\~\:\  \   /::\~\:\  \   /:/  \:\  \         
 /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/ \:\__\        
 \/__\:\/:/  / \/__\:\/:/  / \:\  \ /:/  /        
      \::/  /       \::/  /   \:\  /:/  /         
      /:/  /         \/__/     \:\/:/  /          
     /:/  /                     \::/  /           
     \/__/                       \/__/            
Official Website:   https://apo.kindlingx.com/    
DEPLOY_VERSION: v0.7.001                   
APO_ONE_AGENT_VERSION: v0.7.0     
==================================================
INFO: APO-proxy-ip = 192.168.10.40
1 error(s) decoding:

* 'cpus' expected type 'float32', got unconvertible type 'string', value: '1'

CPU 信息如下：
processor       : 15
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel Xeon Processor (Cascadelake)
stepping        : 6
microcode       : 0x1
cpu MHz         : 2992.968
cache size      : 16384 KB
physical id     : 1
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 15
initial apicid  : 15
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat pku ospke avx512_vnni
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit mmio_stale_data retbleed gds bhi
bogomips        : 5985.93
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

**Comment by dxsup** [comment]
这个报错信息具体是在什么阶段抛出的？具体是apo-one-agent中的哪个容器输出的？
