### ISSUE TITLE
Regarding the scenario of monitoring only Redis

### ISSUE THREAD

**Issue by cfy3133** [CloudDetail/apo#6]
你好，请问下，如果我只是想在传统服务器仅仅是监控安装了redis的这台服务，那么只要装了apo-grafana-alloy就行了是嘛

**Comment by dxsup** [comment]
是的，然后按照配置文档接入 Redis 即可

**Comment by cfy3133** [comment]
> 是的，然后按照配置文档接入 Redis 即可

好的，感谢，能够自动发现新添加节点的服务嘛

**Comment by apoProject-cheng** [comment]
> > 是的，然后按照配置文档接入 Redis 即可
> 
> 好的，感谢，能够自动发现新添加节点的服务嘛

这个指应用，还是类似redis中间件？

**Comment by cfy3133** [comment]
> > > 是的，然后按照配置文档接入 Redis 即可
> > 
> > 
> > 好的，感谢，能够自动发现新添加节点的服务嘛
> 
> 这个指应用，还是类似redis中间件？

你好，指的是redis中间件哈

**Comment by apoProject-cheng** [comment]
是个好想法，对于不要配置用户密码的中间件确实理论可行。我们可以放到roadmap里面去，目前还不支持。

**Comment by cfy3133** [comment]
> 是个好想法，对于不要配置用户密码的中间件确实理论可行。我们可以放到roadmap里面去，目前还不支持。

好的，感谢你，后期可以推广到其他rocketmq、mysql等等的监控中

**Comment by dxsup** [comment]
Added "Automatically discovering services" to the backlog.
