### ISSUE TITLE
你好，能否集成Flame Graph AI: Grafana新推出智能火焰图分析AI

### ISSUE THREAD

**Issue by cfy3133** [CloudDetail/apo#75]
详情如下连接：
https://mp.weixin.qq.com/s/4B82xP0uMLoK8Q_ETcQfFg

**Comment by dxsup** [comment]
感谢建议，使用大模型分析观测数据的确能够帮助用户更好地理解数据价值，APO也正在这个方向上探索。

目前 Continuous Profiling/Flame Graph 数据采集已经在开发路线上，在实现该功能以后，我们会考虑集成大模型来对火焰图进行分析。

**Comment by cfy3133** [comment]
> 感谢建议，使用大模型分析观测数据的确能够帮助用户更好地理解数据价值，APO也正在这个方向上探索。
> 
> 目前 Continuous Profiling/Flame Graph 数据采集已经在开发路线上，在实现该功能以后，我们会考虑集成大模型来对火焰图进行分析。

好的，能否给一个grafana的入口可以配置Flame Graph AI呢

**Comment by dxsup** [comment]
Grafana 的 Flame Graph AI 只有使用 [Grafana Cloud](https://grafana.com/docs/grafana-cloud/monitor-applications/profiles/flamegraph-ai/) 才有这个功能。开源社区能集成的仅有 Grafana 开源版，这个版本目前没提供这个功能。未来 APO 会考虑独立开发 AI 分析入口（如果有能够集成的方案也会考虑）。

**Comment by cfy3133** [comment]
> Grafana 的 Flame Graph AI 只有使用 [Grafana Cloud](https://grafana.com/docs/grafana-cloud/monitor-applications/profiles/flamegraph-ai/) 才有这个功能。开源社区能集成的仅有 Grafana 开源版，这个版本目前没提供这个功能。未来 APO 会考虑独立开发 AI 分析入口（如果有能够集成的方案也会考虑）。

好的
