### ISSUE TITLE
apo-one-agent  Helm chart 需要更新

### ISSUE THREAD

**Issue by mercury7720** [CloudDetail/apo#8]
- helm chart: 0.3.001
- k8s: 1.28.7
- helm: v3.14.1

按 [文档](https://originx.kindlingx.com/docs/APO%20%E5%90%91%E5%AF%BC%E5%BC%8F%E5%8F%AF%E8%A7%82%E6%B5%8B%E6%80%A7%E4%B8%AD%E5%BF%83/%E5%AE%89%E8%A3%85%E6%89%8B%E5%86%8C/%E7%9B%91%E6%8E%A7%20Kubernetes%20%E9%9B%86%E7%BE%A4%E4%B8%AD%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%92%8C%E5%BA%94%E7%94%A8%E4%BD%BF%E7%94%A8OneAgent%E9%BB%98%E8%AE%A4OTEL%E6%8E%A2%E9%92%88%E7%89%88%E6%9C%AC) 说明修改 apoServerIP 和 targetNamespace，执行 `helm install apo-one-agent apo/apo-one-agent -n apo --create-namespace -f apo-one-agent-values.yaml` 报错：

```bash
Error: INSTALLATION FAILED: template: apo-one-agent/templates/apo-otel-collector-agent-configmap.yaml:66:40: executing "apo-one-agent/templates/apo-otel-collector-agent-configmap.yaml" at <.Values.apoOtelCollectorAgent.config.apoOtelCollectorUrl>: wrong type for value; expected string; got interface {}
```

helm pull 后发现默认的 `value.yaml` 里 `apoOtelCollectorAgent` 的配置为 `apoOtelCollectorURL`而不是 `apoOtelCollectorUrl`，修改后即可正常安装。

---

然后发现 apo-nginx-proxy 无法启动，查看 Pod 是 Nginx 在报错，随后查看 configmap ，发现生成的配置有误：

<img width="375" alt="image" src="https://github.com/user-attachments/assets/b1f2f4c9-53c8-448b-b70e-cea446d59d77">

apo-nginx-proxy 的 configmap template 里 配置的是 apoCollectorPort。

<img width="939" alt="image" src="https://github.com/user-attachments/assets/a426ec67-9eca-4ec2-8d76-3d39f281cb1b">

但是 global 里没有 apoCollectorPort 配置，所以报错。

<img width="510" alt="image" src="https://github.com/user-attachments/assets/73c92be5-f911-4da6-8952-57a53d6dbd3c">

修改为 apoOtelCollectorGatewayGRPCPort 后运行正常，不知道端口对不对。

**Comment by GNLMQNMB** [comment]
感谢您的支持
已修复【helm pull 后发现默认的 value.yaml 里 apoOtelCollectorAgent 的配置为 apoOtelCollectorURL而不是 apoOtelCollectorUrl，修改后即可正常安装。】
已修复【然后发现 apo-nginx-proxy 无法启动，查看 Pod 是 Nginx 在报错，随后查看 configmap ，发现生成的配置有误】
【修改为 apoOtelCollectorGatewayGRPCPort 后运行正常，不知道端口对不对。】不对，如果您已经安装，可以将nginx配置中此端口配置为30044（默认），后续部署可以通过helm repo update apo更新charts仓库修复此问题
