### ISSUE TITLE
有关JVM的监控

### ISSUE THREAD

**Issue by cfy3133** [CloudDetail/apo#9]
你好，请问下能否加上JAVA应用监控有关的JVM详细的监控信息，类似于skywalking那样的形式

**Comment by apoProject-cheng** [comment]
我们是有打算集成这个https://github.com/prometheus/jmx_exporter，然后多配置一个大屏

**Comment by apoProject-cheng** [comment]
@cfy3133 不过这个需要作为java agent和应用一起启动，你们怎么看？

**Comment by cfy3133** [comment]
> @cfy3133 不过这个需要作为java agent和应用一起启动，你们怎么看？

你好，感觉集成jmx_exporter挺好的呀，可以节约开发的时间，用现成的就好了，希望能够简单一些，使用的用户如果部署起来麻烦的话，不是一件好事。现在apo部署起来特别简单，无论是传统服务器还是k8s都部署起来非常简单，感谢回复
